COIN_ALIASES = {
    "Chainlink Labs": "LINK",
    "Uniswap Labs": "UNI",
    "MakerDAO": "MKR",
    "Aave": "AAVE",
    "Aave Companies": "AAVE",
    "Curve": "CRV",
    "Yearn Finance": "YFI",
    "Lido": "LDO",
    "Lido DAO": "LDO",
    "Compound": "COMP",
    "OpenZeppelin": "OZ",
    "Balancer": "BAL",
    "Arbitrum": "ARB",
    "Optimism": "OP",
    "Polygon": "MATIC",
    "Solana": "SOL",
    "Ethereum Foundation": "ETH",
    "Bitcoin Core": "BTC",
    "Cardano": "ADA",
    "XRP Ledger": "XRP",
}
